version: '3'

services:
  db:
    container_name: persado-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rails_user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5437:5432"
